import socket
server_socket_object = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket_object.bind(('localhost', 8080))
server_socket_object.listen(1)
print("Server is listening on localhost:8080...")
client_socket, client_address = server_socket_object.accept()
print(f"Connection established with {client_address}")
client_socket.sendall(b'This is server side message')
client_msg = client_socket.recv(1024)
print(f"Client message: {client_msg.decode()}")
client_socket.close()
server_socket_object.close()